version: "3.4"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=queue
      - REDIS_PORT=6379
    depends_on:
      - queue
  queue:
    image: redis:latest
    ports:
      - "6379:6379"
  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    environment:
      - REDIS_HOST=queue
      - REDIS_PORT=6379
    depends_on:
      - queue
